# Generated by Django 5.2.1 on 2025-06-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sabor', models.CharField(max_length=50)),
                ('tamanio', models.CharField(max_length=20)),
                ('bebida_sugerida_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
